### ISSUE TITLE
KAIST dataset

### ISSUE THREAD

**Issue by yarqian** [Vibashan/Image-Fusion-Transformer#2]
Many thanks for your work. I go to their project homepage but it seems the dataset is unavailable  So I am sorry to ask how to download KAIST  dataset?

**Comment by Vibashan** [comment]
Hi 

You can look into this link (https://soonminhwang.github.io/rgbt-ped-detection/) for downloading the dataset. It is on the author's page.

**Comment by yarqian** [comment]
I followed the instructions in the page, but the download page shows an issue like "The requested URL was not found on this server." Is the file unavailable?

**Comment by Vibashan** [comment]
Hi 

You can look into the Soonmin Github repo (https://github.com/SoonminHwang/rgbt-ped-detection).
