### ISSUE TITLE
`with torch.no_grad()` in your `train_fusionnet_axial.py` ? 

### ISSUE THREAD

**Issue by shinianzhihou** [Vibashan/Image-Fusion-Transformer#7]
In your training script, you use `with torch.no_grad()` in line 56 to build your nest_model.

It means only fusion_model are trained during the training process? 

If I want to train on my own dataset, should I remove `with torch.no_grad()` ?

**Comment by Vibashan** [comment]
Yes, only the fusion model is trained during the training process.

If I want to train on my own dataset, should I remove with torch.no_grad() ?
Yes.
